name: 'Sykli'
description: 'CI in your language. No YAML. No DSL. Just code.'
author: 'yairfalse'

branding:
  icon: 'zap'
  color: 'blue'

inputs:
  path:
    description: 'Path to project containing sykli.go or sykli.rs'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    # Cache sykli task results
    - name: Cache sykli
      uses: actions/cache@v4
      with:
        path: ~/.sykli/cache
        key: sykli-${{ runner.os }}-${{ hashFiles('**/sykli.go', '**/sykli.rs', '**/sykli.ts') }}
        restore-keys: |
          sykli-${{ runner.os }}-

    # Setup Elixir for sykli
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15'
        otp-version: '26'

    # Build and run sykli
    - name: Run sykli
      shell: bash
      run: |
        # Clone and build sykli (TODO: use release binary)
        # TODO: Update the repository URL below to the official sykli repository before merging.
        git clone --depth 1 https://github.com/sykli-org/sykli.git /tmp/sykli
        cd /tmp/sykli/core
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix escript.build

        # Run sykli on the project
        /tmp/sykli/core/sykli ${{ inputs.path }}
